baseURL = "https://xenoz01.github.io/cyber-portfolio/"
languageCode = "fr-fr"
title = "Nathan Charpentier | Cybersécurité"
theme = "PaperMod"

enableRobotsTXT = true

[menu]

[[menu.main]]
identifier = "home"
name = "Accueil"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "À propos"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "cv"
name = "CV"
url = "/cv/"
weight = 3

[[menu.main]]
identifier = "experience"
name = "Expériences"
url = "/experience/"
weight = 4

[[menu.main]]
identifier = "projects"
name = "Projets"
url = "/projects/"
weight = 5

[[menu.main]]
identifier = "posts"
name = "Articles"
url = "/posts/"
weight = 6

[[menu.main]]
identifier = "awareness"
name = "Sensibilisation"
url = "/awareness/"
weight = 7

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 8

[params]
env = "production"
defaultTheme = "auto"

ShowReadingTime = true
ShowWordCount = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true

ShowShareButtons = false
ShowRssButtonInSectionTermList = true

UseHugoToc = true

[params.homeInfoParams]
Title = "Nathan Charpentier"
Content = """
Consultant Cybersécurité Junior

GRC • Gestion des Risques • ISO 27001 • Blue Team

Je développe une expertise en gouvernance, gestion des risques et conformité afin d'accompagner les organisations dans l'amélioration de leur posture de sécurité.

Ce site présente mon parcours, mes expériences, mes projets et ma veille cybersécurité.
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/XeNoZ01"
